[project]
name = "cs-e4660"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.120.4",
    "paho-mqtt>=2.1.0",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
